"""Added 'role' column to Branch

Revision ID: 210fb50d1f17
Revises: 5ca5e8da8632
Create Date: 2025-02-01 10:49:52.077709

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "210fb50d1f17"
down_revision = "5ca5e8da8632"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("branch", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "role", sa.String(length=20), nullable=False, server_default="user"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("branch", schema=None) as batch_op:
        batch_op.drop_column("role")

    # ### end Alembic commands ###
