"""minor changes to column names in OptimizedPrices

Revision ID: 3f666bd64298
Revises: c30c30e13a42
Create Date: 2025-03-02 22:17:23.700896

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3f666bd64298"
down_revision = "c30c30e13a42"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("optimized_prices", schema=None) as batch_op:
        batch_op.add_column(sa.Column("current_price", sa.Float(), nullable=False))
        batch_op.add_column(sa.Column("optimized_price", sa.Float(), nullable=False))
        batch_op.drop_column("optimized_prices")
        batch_op.drop_column("predicted_prices")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("optimized_prices", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "predicted_prices",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "optimized_prices",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_column("optimized_price")
        batch_op.drop_column("current_price")

    # ### end Alembic commands ###
