"""Added 'active' column to Branch

Revision ID: c13a43431d96
Revises: 1cb3a3f53505
Create Date: 2025-02-01 12:45:30.175470

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c13a43431d96"
down_revision = "1cb3a3f53505"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("branch", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("active", sa.Boolean(), nullable=True, system_default=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("branch", schema=None) as batch_op:
        batch_op.drop_column("active")

    # ### end Alembic commands ###
