"""modified Optimization and added children OptimizedSales, OptimizedPrices

Revision ID: c30c30e13a42
Revises: ee53230638a3
Create Date: 2025-02-25 22:46:41.069255

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c30c30e13a42"
down_revision = "ee53230638a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "optimized_prices",
        sa.Column("optimization_id", sa.UUID(), nullable=False),
        sa.Column(
            "timeframe",
            sa.Enum("Next Week", "Next Month", "Next Quarter", name="opt_timeframes"),
            nullable=False,
        ),
        sa.Column("product_id", sa.String(length=100), nullable=False),
        sa.Column("predicted_prices", sa.Float(), nullable=False),
        sa.Column("optimized_prices", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["optimization_id"],
            ["optimization.id"],
        ),
        sa.PrimaryKeyConstraint("optimization_id", "timeframe", "product_id"),
    )
    op.create_table(
        "optimized_sales",
        sa.Column("optimization_id", sa.UUID(), nullable=False),
        sa.Column(
            "timeframe",
            sa.Enum("Next Week", "Next Month", "Next Quarter", name="opt_timeframes"),
            nullable=False,
        ),
        sa.Column("predicted_sales", sa.Float(), nullable=False),
        sa.Column("optimized_sales", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["optimization_id"],
            ["optimization.id"],
        ),
        sa.PrimaryKeyConstraint("optimization_id", "timeframe"),
    )
    with op.batch_alter_table("optimization", schema=None) as batch_op:
        batch_op.drop_column("product_id")
        batch_op.drop_column("optimized_price")
        batch_op.drop_column("timeframe")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("optimization", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "timeframe",
                postgresql.ENUM("Weekly", "Monthly", name="timeframes"),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "optimized_price",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "product_id", sa.VARCHAR(length=50), autoincrement=False, nullable=False
            )
        )

    op.drop_table("optimized_sales")
    op.drop_table("optimized_prices")
    # ### end Alembic commands ###
